# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseInPayment.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import *

class Ui_PaymentWindow(object):
    def setupUi(self, PaymentWindow):
        PaymentWindow.setObjectName("PaymentWindow")
        PaymentWindow.resize(1223, 839)
        PaymentWindow.setStyleSheet("QMainWindow{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(13, 115, 119, 255), stop:1 rgba(33, 33, 33, 255));\n"
"}\n"
"\n"
"QLabel{\n"
"color: #32e0c4;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(PaymentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.optionsInPaymentLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.optionsInPaymentLabel.setFont(font)
        self.optionsInPaymentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.optionsInPaymentLabel.setObjectName("optionsInPaymentLabel")
        self.verticalLayout_5.addWidget(self.optionsInPaymentLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(740, 470))
        self.frame.setMaximumSize(QtCore.QSize(760, 470))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(33, 33, 33);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QLabel{\n"
"color: #eeeeee;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(13, 115, 119);\n"
"border-radius: 80px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 224, 196);\n"
"}\n"
"\n"
"QPushButton#cancelButton{\n"
"color: #eeeeee;\n"
"background-color: #212121;\n"
"border: 2px solid #9a0002;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton#cancelButton:hover{\n"
"border: 3px solid rgb(255, 0, 0);\n"
"background-color: #9a0002;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.installmentButton = QtWidgets.QPushButton(self.frame)
        self.installmentButton.setMinimumSize(QtCore.QSize(161, 161))
        self.installmentButton.setMaximumSize(QtCore.QSize(161, 161))
        self.installmentButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.installmentButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/paymentIcons/rupeeinstallment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.installmentButton.setIcon(icon)
        self.installmentButton.setIconSize(QtCore.QSize(80, 80))
        self.installmentButton.setObjectName("installmentButton")
        self.verticalLayout.addWidget(self.installmentButton)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(161, 31))
        self.label.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.transactionButton = QtWidgets.QPushButton(self.frame)
        self.transactionButton.setMinimumSize(QtCore.QSize(161, 161))
        self.transactionButton.setMaximumSize(QtCore.QSize(161, 161))
        self.transactionButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.transactionButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/paymentIcons/payment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transactionButton.setIcon(icon1)
        self.transactionButton.setIconSize(QtCore.QSize(70, 70))
        self.transactionButton.setObjectName("transactionButton")
        self.verticalLayout_2.addWidget(self.transactionButton)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(161, 31))
        self.label_2.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listTransactionsButton = QtWidgets.QPushButton(self.frame)
        self.listTransactionsButton.setMinimumSize(QtCore.QSize(161, 161))
        self.listTransactionsButton.setMaximumSize(QtCore.QSize(161, 161))
        self.listTransactionsButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.listTransactionsButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/paymentIcons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listTransactionsButton.setIcon(icon2)
        self.listTransactionsButton.setIconSize(QtCore.QSize(90, 90))
        self.listTransactionsButton.setObjectName("listTransactionsButton")
        self.verticalLayout_3.addWidget(self.listTransactionsButton)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(161, 31))
        self.label_3.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setMinimumSize(QtCore.QSize(150, 50))
        self.cancelButton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        PaymentWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PaymentWindow)
        self.statusbar.setObjectName("statusbar")
        PaymentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PaymentWindow)
        QtCore.QMetaObject.connectSlotsByName(PaymentWindow)

    def retranslateUi(self, PaymentWindow):
        _translate = QtCore.QCoreApplication.translate
        PaymentWindow.setWindowTitle(_translate("PaymentWindow", "MainWindow"))
        self.optionsInPaymentLabel.setText(_translate("PaymentWindow", "OPTIONS IN PAYMENT"))
        self.label.setText(_translate("PaymentWindow", "Add Installments"))
        self.label_2.setText(_translate("PaymentWindow", "New Transactions"))
        self.label_3.setText(_translate("PaymentWindow", "List Transactions"))
        self.cancelButton.setText(_translate("PaymentWindow", "Back Home"))
import payment_rc
