# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseInBatches.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from addNewBatch import *


class Ui_BatchesWindow(object):
    # AddBatchDialog = QtWidgets.QDialog()
    def setupUi(self, BatchesWindow):
        BatchesWindow.setObjectName("BatchesWindow")
        BatchesWindow.resize(1223, 839)
        BatchesWindow.setStyleSheet("QMainWindow{\n"
                                    "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(13, 115, 119, 255), stop:1 rgba(33, 33, 33, 255));\n"
                                    "}\n"
                                    "\n"
                                    "QLabel{\n"
                                    "color: #32e0c4;\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.centralwidget = QtWidgets.QWidget(BatchesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.optionsInBatchesLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.optionsInBatchesLabel.setFont(font)
        self.optionsInBatchesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.optionsInBatchesLabel.setObjectName("optionsInBatchesLabel")
        self.verticalLayout_5.addWidget(self.optionsInBatchesLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(740, 470))
        self.frame.setMaximumSize(QtCore.QSize(760, 470))
        self.frame.setStyleSheet("QFrame{\n"
                                 "background-color: rgb(33, 33, 33);\n"
                                 "border-radius: 25px;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "color: #eeeeee;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "background-color: rgb(13, 115, 119);\n"
                                 "border-radius: 80px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover{\n"
                                 "background-color: rgb(50, 224, 196);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#cancelButton{\n"
                                 "color: #eeeeee;\n"
                                 "background-color: #212121;\n"
                                 "border: 2px solid #9a0002;\n"
                                 "border-radius: 25px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#cancelButton:hover{\n"
                                 "border: 3px solid rgb(255, 0, 0);\n"
                                 "background-color: #9a0002;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addBatchButton = QtWidgets.QPushButton(self.frame)
        self.addBatchButton.setMinimumSize(QtCore.QSize(161, 161))
        self.addBatchButton.setMaximumSize(QtCore.QSize(161, 161))
        self.addBatchButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.addBatchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/addbatch2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBatchButton.setIcon(icon)
        self.addBatchButton.setIconSize(QtCore.QSize(80, 80))
        self.addBatchButton.setObjectName("addBatchButton")
        self.verticalLayout.addWidget(self.addBatchButton)
        self.addBatchLabel = QtWidgets.QLabel(self.frame)
        self.addBatchLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.addBatchLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addBatchLabel.setFont(font)
        self.addBatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addBatchLabel.setObjectName("addBatchLabel")
        self.verticalLayout.addWidget(self.addBatchLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allotBatchButton = QtWidgets.QPushButton(self.frame)
        self.allotBatchButton.setMinimumSize(QtCore.QSize(161, 161))
        self.allotBatchButton.setMaximumSize(QtCore.QSize(161, 161))
        self.allotBatchButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.allotBatchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/addStudent.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.allotBatchButton.setIcon(icon1)
        self.allotBatchButton.setIconSize(QtCore.QSize(70, 70))
        self.allotBatchButton.setObjectName("allotBatchButton")
        self.verticalLayout_2.addWidget(self.allotBatchButton)
        self.allotBatchLabel = QtWidgets.QLabel(self.frame)
        self.allotBatchLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.allotBatchLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allotBatchLabel.setFont(font)
        self.allotBatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.allotBatchLabel.setObjectName("allotBatchLabel")
        self.verticalLayout_2.addWidget(self.allotBatchLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setMinimumSize(QtCore.QSize(150, 50))
        self.cancelButton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 0, 1, 1)
        BatchesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BatchesWindow)
        self.statusbar.setObjectName("statusbar")
        BatchesWindow.setStatusBar(self.statusbar)
        self.addBatchButton.clicked.connect(self.addBatch)

        # self.cancelButton.clicked.connect(self.AddBatchDialog.close())
        # AddBatchDialog.cancelButton.clicked.connect(self.closeBatch)
        self.retranslateUi(BatchesWindow)
        QtCore.QMetaObject.connectSlotsByName(BatchesWindow)


    def addBatch(self):
        self.AddBatchDialog = QtWidgets.QDialog()
        self.ui = Ui_AddBatchDialog()
        self.ui.setupUi(self.AddBatchDialog)
        self.AddBatchDialog.show()
        self.ui.cancelButton.clicked.connect(self.AddBatchDialog.close)

    # def closeBatch(self):
    #     self.AddBatchDialog.close()

    def retranslateUi(self, BatchesWindow):
        _translate = QtCore.QCoreApplication.translate
        BatchesWindow.setWindowTitle(_translate("BatchesWindow", "MainWindow"))
        self.optionsInBatchesLabel.setText(_translate("BatchesWindow", "OPTIONS IN BATCHES"))
        self.addBatchLabel.setText(_translate("BatchesWindow", "Add Batch"))
        self.allotBatchLabel.setText(_translate("BatchesWindow", "Batch Allotment"))
        self.cancelButton.setText(_translate("BatchesWindow", "Back Home"))


import batches_rc
import payment_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    choose = QtWidgets.QMainWindow()
    ui = Ui_BatchesWindow()
    ui.setupUi(choose)
    choose.show()
    sys.exit(app.exec_())