# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseInSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, SearchWindow):
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.resize(1140, 806)
        SearchWindow.setStyleSheet("QMainWindow{\n"
                                   "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(13, 115, 119, 255), stop:1 rgba(33, 33, 33, 255));\n"
                                   "}\n"
                                   "\n"
                                   "QLabel{\n"
                                   "color: #32e0c4;\n"
                                   "}\n"
                                   "\n"
                                   "")
        self.centralwidget = QtWidgets.QWidget(SearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.optionsInSearch = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.optionsInSearch.setFont(font)
        self.optionsInSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.optionsInSearch.setObjectName("optionsInSearch")
        self.verticalLayout_6.addWidget(self.optionsInSearch)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(900, 470))
        self.frame_2.setMaximumSize(QtCore.QSize(900, 470))
        self.frame_2.setStyleSheet("QFrame{\n"
                                   "background-color: rgb(33, 33, 33);\n"
                                   "border-radius: 25px;\n"
                                   "}\n"
                                   "\n"
                                   "QLabel{\n"
                                   "color: #eeeeee;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton{\n"
                                   "background-color: rgb(13, 115, 119);\n"
                                   "border-radius: 80px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover{\n"
                                   "background-color: rgb(50, 224, 196);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#backButton{\n"
                                   "color: #eeeeee;\n"
                                   "background-color: #212121;\n"
                                   "border: 2px solid #9a0002;\n"
                                   "border-radius: 25px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#backButton:hover{\n"
                                   "border: 3px solid rgb(255, 0, 0);\n"
                                   "background-color: #9a0002;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.studentButton = QtWidgets.QPushButton(self.frame_2)
        self.studentButton.setMinimumSize(QtCore.QSize(161, 161))
        self.studentButton.setMaximumSize(QtCore.QSize(161, 161))
        self.studentButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.studentButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/searchStudent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.studentButton.setIcon(icon)
        self.studentButton.setIconSize(QtCore.QSize(90, 90))
        self.studentButton.setObjectName("studentButton")
        self.verticalLayout_8.addWidget(self.studentButton)
        self.studentLabel = QtWidgets.QLabel(self.frame_2)
        self.studentLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.studentLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studentLabel.setFont(font)
        self.studentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentLabel.setObjectName("studentLabel")
        self.verticalLayout_8.addWidget(self.studentLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.batchButton = QtWidgets.QPushButton(self.frame_2)
        self.batchButton.setMinimumSize(QtCore.QSize(161, 161))
        self.batchButton.setMaximumSize(QtCore.QSize(161, 161))
        self.batchButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.batchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/searchBatch3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batchButton.setIcon(icon1)
        self.batchButton.setIconSize(QtCore.QSize(90, 90))
        self.batchButton.setObjectName("batchButton")
        self.verticalLayout_9.addWidget(self.batchButton)
        self.batchLabel = QtWidgets.QLabel(self.frame_2)
        self.batchLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.batchLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batchLabel.setFont(font)
        self.batchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.batchLabel.setObjectName("batchLabel")
        self.verticalLayout_9.addWidget(self.batchLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.placementButton = QtWidgets.QPushButton(self.frame_2)
        self.placementButton.setMinimumSize(QtCore.QSize(161, 161))
        self.placementButton.setMaximumSize(QtCore.QSize(161, 161))
        self.placementButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.placementButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/searchJob1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.placementButton.setIcon(icon2)
        self.placementButton.setIconSize(QtCore.QSize(150, 150))
        self.placementButton.setObjectName("placementButton")
        self.verticalLayout_10.addWidget(self.placementButton)
        self.placementLabel = QtWidgets.QLabel(self.frame_2)
        self.placementLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.placementLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placementLabel.setFont(font)
        self.placementLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.placementLabel.setObjectName("placementLabel")
        self.verticalLayout_10.addWidget(self.placementLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.transactionsButton = QtWidgets.QPushButton(self.frame_2)
        self.transactionsButton.setMinimumSize(QtCore.QSize(161, 161))
        self.transactionsButton.setMaximumSize(QtCore.QSize(161, 161))
        self.transactionsButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.transactionsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/search1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transactionsButton.setIcon(icon3)
        self.transactionsButton.setIconSize(QtCore.QSize(90, 90))
        self.transactionsButton.setObjectName("transactionsButton")
        self.verticalLayout_11.addWidget(self.transactionsButton)
        self.transactionLabel = QtWidgets.QLabel(self.frame_2)
        self.transactionLabel.setMinimumSize(QtCore.QSize(161, 31))
        self.transactionLabel.setMaximumSize(QtCore.QSize(161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.transactionLabel.setFont(font)
        self.transactionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.transactionLabel.setObjectName("transactionLabel")
        self.verticalLayout_11.addWidget(self.transactionLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.backButton = QtWidgets.QPushButton(self.frame_2)
        self.backButton.setMinimumSize(QtCore.QSize(150, 50))
        self.backButton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 0, 1, 1, 1)
        SearchWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SearchWindow)
        self.statusbar.setObjectName("statusbar")
        SearchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("SearchWindow", "MainWindow"))
        self.optionsInSearch.setText(_translate("SearchWindow", "OPTIONS IN SEARCH"))
        self.studentLabel.setText(_translate("SearchWindow", "Students Section"))
        self.batchLabel.setText(_translate("SearchWindow", "Batches Section"))
        self.placementLabel.setText(_translate("SearchWindow", "Placement Drives"))
        self.transactionLabel.setText(_translate("SearchWindow", "Transactions"))
        self.backButton.setText(_translate("SearchWindow", "Back Home"))


import search_rc
