# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompanyDriveMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
######### Added Code #######
#from add_company import *  # Adding the Add company Dialog Box.
#from AddCompanyDrive_Final import *
#from viewDrive import *
######### End of Added Code ######

class Ui_ComanyDriveMain(object):
    def setupUi(self, ComanyDriveMain):
        ComanyDriveMain.setObjectName("ComanyDriveMain")
        ComanyDriveMain.resize(1077, 668)
        ComanyDriveMain.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ComanyDriveMain)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.heading_Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heading_Label.sizePolicy().hasHeightForWidth())
        self.heading_Label.setSizePolicy(sizePolicy)
        self.heading_Label.setMinimumSize(QtCore.QSize(700, 100))
        self.heading_Label.setMaximumSize(QtCore.QSize(700, 100))
        font = QtGui.QFont()
        font.setPointSize(49)
        self.heading_Label.setFont(font)
        self.heading_Label.setStyleSheet("color: #32e0c4;")
        self.heading_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_Label.setObjectName("heading_Label")
        self.horizontalLayout_3.addWidget(self.heading_Label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.addCompany_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addCompany_Button.sizePolicy().hasHeightForWidth())
        self.addCompany_Button.setSizePolicy(sizePolicy)
        self.addCompany_Button.setMinimumSize(QtCore.QSize(300, 200))
        self.addCompany_Button.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.addCompany_Button.setFont(font)
        self.addCompany_Button.setStyleSheet("background-color: #32e0c4;\n"
"Color: #eeeeee;\n"
"border-radius: 20px;")
        self.addCompany_Button.setObjectName("addCompany_Button")
        self.horizontalLayout.addWidget(self.addCompany_Button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.addDrive_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDrive_Button.sizePolicy().hasHeightForWidth())
        self.addDrive_Button.setSizePolicy(sizePolicy)
        self.addDrive_Button.setMinimumSize(QtCore.QSize(300, 200))
        self.addDrive_Button.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.addDrive_Button.setFont(font)
        self.addDrive_Button.setStyleSheet("background-color: #32e0c4;\n"
"Color: #eeeeee;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.addDrive_Button.setObjectName("addDrive_Button")
        self.horizontalLayout.addWidget(self.addDrive_Button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.viewDrive_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewDrive_Button.sizePolicy().hasHeightForWidth())
        self.viewDrive_Button.setSizePolicy(sizePolicy)
        self.viewDrive_Button.setMinimumSize(QtCore.QSize(300, 200))
        self.viewDrive_Button.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.viewDrive_Button.setFont(font)
        self.viewDrive_Button.setMouseTracking(True)
        self.viewDrive_Button.setStyleSheet("background-color: #32e0c4;\n"
"Color: #eeeeee;\n"
"border-radius: 20px;")
        self.viewDrive_Button.setObjectName("viewDrive_Button")
        self.horizontalLayout.addWidget(self.viewDrive_Button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.backHome_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backHome_Button.sizePolicy().hasHeightForWidth())
        self.backHome_Button.setSizePolicy(sizePolicy)
        self.backHome_Button.setMinimumSize(QtCore.QSize(150, 70))
        self.backHome_Button.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.backHome_Button.setFont(font)
        self.backHome_Button.setStyleSheet("border: 2px solid #9a0002;\n"
"background-color: #212121;\n"
"Color: #eeeeee;\n"
"border-radius: 20px;")
        self.backHome_Button.setObjectName("backHome_Button")
        self.horizontalLayout_2.addWidget(self.backHome_Button)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 2, 1, 1, 1)
        ComanyDriveMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ComanyDriveMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 22))
        self.menubar.setObjectName("menubar")
        ComanyDriveMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ComanyDriveMain)
        self.statusbar.setObjectName("statusbar")
        ComanyDriveMain.setStatusBar(self.statusbar)

        self.retranslateUi(ComanyDriveMain)
        QtCore.QMetaObject.connectSlotsByName(ComanyDriveMain)

        ######## Added Code ########

    #     self.addCompany_Button.clicked.connect(self.startAddCompany)      # Calls the Add Company Dailog Box
    #     self.addDrive_Button.clicked.connect(self.startAddDrive)
    #     self.backHome_Button.clicked.connect(lambda: exit())
    #
    # def startAddDrive(self):
    #     self.adddrive = Ui_AddDrive()
    #     self.adddrive.setupUi(self)
    #     self.setWindowState(QtCore.Qt.WindowMaximized)
    #
    # def startAddCompany(self):
    #     self.addCompanyobj = Ui_AddCompany_Dailog()
    #     AddCompany_Dailog = QtWidgets.QDialog()
    #     self.addCompanyobj.setupUi(AddCompany_Dailog)
    #     AddCompany_Dailog.show()

        ######## End of Added Code ########


    def retranslateUi(self, ComanyDriveMain):
        _translate = QtCore.QCoreApplication.translate
        ComanyDriveMain.setWindowTitle(_translate("ComanyDriveMain", "MainWindow"))
        self.heading_Label.setText(_translate("ComanyDriveMain", "Company Drive"))
        self.addCompany_Button.setText(_translate("ComanyDriveMain", "Add Company"))
        self.addDrive_Button.setText(_translate("ComanyDriveMain", "Add Company Drive"))
        self.viewDrive_Button.setText(_translate("ComanyDriveMain", "View Company Drives"))
        self.backHome_Button.setText(_translate("ComanyDriveMain", "Back Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComanyDriveMain = QtWidgets.QMainWindow()
    ui = Ui_ComanyDriveMain()
    ui.setupUi(ComanyDriveMain)
    ComanyDriveMain.show()
    sys.exit(app.exec_())
