# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateStudentInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import mysql.connector


mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="local",
    password="",
    database="mpdev"
)


class Ui_UpdateStudentInfo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 701)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "background-color: #212121;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "background-color: #212121;\n"
                                 "Color: #eeeeee;\n"
                                 "border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#backButton{\n"
                                 "color: #eeeeee;\n"
                                 "background-color: #212121;\n"
                                 "border: 2px solid #9a0002;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#backButton:hover{\n"
                                 "border: 3px solid rgb(255, 0, 0);\n"
                                 "background-color: #9a0002;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#updateButton{\n"
                                 "color: #eeeeee;\n"
                                 "background-color: #212121;\n"
                                 "border: 2px solid #008fd6;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#updateButton:hover{\n"
                                 "border: 3px solid #005d8c;\n"
                                 "background-color: #00c8ff;\n"
                                 "color: #ffffff;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#clearButton{\n"
                                 "color: #eeeeee;\n"
                                 "background-color: #212121;\n"
                                 "border: 2px solid #ca8700;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#clearButton:hover{\n"
                                 "border: 3px solid #ca8700;\n"
                                 "background-color: #ffaa00;\n"
                                 "color: #ffffff;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit{\n"
                                 "padding-left: 6px;\n"
                                 "padding-right: 6px;\n"
                                 "border: 2px solid #0d7377;\n"
                                 "border-radius: 5px;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:hover{\n"
                                 "border: 3px solid #32e0c4;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "color: #eeeeee;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#studentsInfoLabel{\n"
                                 "color: #32e0c4;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QLabel#selectedStudentLabel{\n"
                                 "color:#aaffff;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#cautionLabel{\n"
                                 "color: rgb(255, 85, 0);\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox{\n"
                                 "border: 2px solid #0d7377;\n"
                                 "border-radius: 5px;\n"
                                 "padding-left: 4px;\n"
                                 "padding-right: 4px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox:hover{\n"
                                 "border: 3px solid #32e0c4;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox QAbstractItemView {\n"
                                 "border: 2px solid #32e0c4;\n"
                                 "selection-background-color: #0d7377;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.studentsInfoLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.studentsInfoLabel.setFont(font)
        self.studentsInfoLabel.setStyleSheet("")
        self.studentsInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentsInfoLabel.setObjectName("studentsInfoLabel")
        self.verticalLayout_3.addWidget(self.studentsInfoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchByLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchByLabel.setMinimumSize(QtCore.QSize(300, 40))
        self.searchByLabel.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.searchByLabel.setFont(font)
        self.searchByLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.searchByLabel.setObjectName("searchByLabel")
        self.verticalLayout.addWidget(self.searchByLabel)
        self.searchByComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.searchByComboBox.setMinimumSize(QtCore.QSize(300, 40))
        self.searchByComboBox.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchByComboBox.setFont(font)
        self.searchByComboBox.setObjectName("searchByComboBox")
        self.searchByComboBox.addItem("")
        self.searchByComboBox.addItem("")
        self.verticalLayout.addWidget(self.searchByComboBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLabel = QtWidgets.QLabel(self.centralwidget)
        self.searchLabel.setMinimumSize(QtCore.QSize(300, 40))
        self.searchLabel.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.searchLabel.setFont(font)
        self.searchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.searchLabel.setObjectName("searchLabel")
        self.verticalLayout_2.addWidget(self.searchLabel)
        self.searchInput = QtWidgets.QLineEdit(self.centralwidget)
        self.searchInput.setMinimumSize(QtCore.QSize(300, 40))
        self.searchInput.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchInput.setFont(font)
        self.searchInput.setText("")
        self.searchInput.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.searchInput.setClearButtonEnabled(True)
        self.searchInput.setObjectName("searchInput")
        self.verticalLayout_2.addWidget(self.searchInput)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.selectedStudentLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectedStudentLabel.setMinimumSize(QtCore.QSize(600, 40))
        self.selectedStudentLabel.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.selectedStudentLabel.setFont(font)
        self.selectedStudentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedStudentLabel.setObjectName("selectedStudentLabel")
        self.horizontalLayout_7.addWidget(self.selectedStudentLabel)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setMinimumSize(QtCore.QSize(180, 40))
        self.updateButton.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMinimumSize(QtCore.QSize(180, 40))
        self.clearButton.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clearButton.setFont(font)
        self.clearButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cautionLabel = QtWidgets.QLabel(self.centralwidget)
        self.cautionLabel.setMinimumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cautionLabel.setFont(font)
        self.cautionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cautionLabel.setObjectName("cautionLabel")
        self.horizontalLayout_3.addWidget(self.cautionLabel)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.searchDataTable = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchDataTable.setFont(font)
        self.searchDataTable.setObjectName("searchDataTable")
        self.searchDataTable.setColumnCount(10)
        self.searchDataTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDataTable.setHorizontalHeaderItem(9, item)
        self.horizontalLayout_6.addWidget(self.searchDataTable)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setMinimumSize(QtCore.QSize(180, 40))
        self.backButton.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.searchDataTable.itemSelectionChanged.connect(self.itemSelected)
        self.updateButton.clicked.connect(self.updateStudent)

        self.retranslateUi(MainWindow)
        self.loadAll()
        self.searchDataTable.verticalHeader().setVisible(False)
        self.searchInput.textChanged.connect(self.searchOnName)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def loadAll(self):
        mycursor = mydb.cursor(buffered=True)
        mycursor.execute("SELECT * FROM student_info_table")
        lst = mycursor.fetchall()
        row = 0
        self.searchDataTable.setRowCount(mycursor.rowcount)
        for x in lst:
            fname = x[1]
            mname = x[2]
            lname = x[3]
            sql = "SELECT count(*) FROM student_course_batch WHERE student_id = " + str(x[0])
            mycursor.execute(sql)
            fullname = fname + " " + mname + " " + lname
            sql = "SELECT count(referrals) FROM student_info_table WHERE referrals = '" + fullname + "'"
            mycursor.execute(sql)
            self.searchDataTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))
            self.searchDataTable.item(row, 0).setFlags(QtCore.Qt.ItemIsEnabled)
            self.searchDataTable.setItem(row, 1, QtWidgets.QTableWidgetItem(fullname))
            self.searchDataTable.setItem(row, 2, QtWidgets.QTableWidgetItem(x[4]))
            self.searchDataTable.setItem(row, 3, QtWidgets.QTableWidgetItem(x[5]))
            self.searchDataTable.setItem(row, 4, QtWidgets.QTableWidgetItem(str(x[8])))
            self.searchDataTable.setItem(row, 5, QtWidgets.QTableWidgetItem(x[6]))
            self.searchDataTable.setItem(row, 6, QtWidgets.QTableWidgetItem(str(x[7])))
            # dateedit = QtWidgets.QDateEdit()
            # dateedit.setDate(x[7])
            # dateedit.setCalendarPopup(True)
            # self.searchDataTable.setCellWidget(row, 6, dateedit)
            self.searchDataTable.item(row, 6).setFlags(QtCore.Qt.ItemIsEnabled)
            self.searchDataTable.setItem(row, 7, QtWidgets.QTableWidgetItem(x[9]))
            self.searchDataTable.setItem(row, 8, QtWidgets.QTableWidgetItem(x[10]))
            if x[11] is None:
                self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem("None"))
            else:
                self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem(x[11]))
            row += 1
        self.setTableSize()

    def updateStudent(self):
        mycursor = mydb.cursor(buffered=True)
        temp = []
        curRow = self.searchDataTable.currentRow()
        id = self.searchDataTable.item(curRow, 0).text()
        fullname = self.searchDataTable.item(curRow, 1).text()
        temp = fullname.split(" ")
        name = ""
        for x in temp:
            name = name + x
        fullname = fullname.split(" ")
        phone = self.searchDataTable.item(curRow, 2).text()
        whatsapp = self.searchDataTable.item(curRow, 3).text()
        address = self.searchDataTable.item(curRow, 4).text()
        email = self.searchDataTable.item(curRow, 5).text()
        admission = self.searchDataTable.item(curRow, 6).text()
        education = self.searchDataTable.item(curRow, 7).text()
        experience = self.searchDataTable.item(curRow, 8).text()
        referrals = self.searchDataTable.item(curRow, 9).text()

        if len(fullname) == 3 and self.addressCheck(education) and self.addressCheck(experience) and self.nameCheck(name) and self.phoneCheck(phone) and self.phoneCheck(whatsapp) and self.emailCheck(email) and self.addressCheck(address) and self.nameCheck(referrals):
            for x in fullname:
                temp.append(x)
            temp.append(self.searchDataTable.item(curRow, 2).text())
            temp.append(self.searchDataTable.item(curRow, 3).text())
            temp.append(self.searchDataTable.item(curRow, 4).text())
            temp.append(self.searchDataTable.item(curRow, 5).text())
            temp.append(self.searchDataTable.item(curRow, 6).text())
            temp.append(self.searchDataTable.item(curRow, 7).text())
            temp.append(self.searchDataTable.item(curRow, 8).text())
            temp.append(self.searchDataTable.item(curRow, 9).text())
            temp.append(id)
            temp = tuple(temp)
            print(temp)
            sql = "UPDATE student_info_table SET first_name = (%s), middle_name = (%s), last_name = (%s), phone = (%s), " \
                  "whatsapp = (%s), address = (%s), email = (%s), date_of_admission = (%s), education = (%s), experience " \
                  "= (%s), referrals = (%s) WHERE student_id = (%s) "
            mycursor.execute(sql, temp)
            if mycursor.rowcount != 0:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText("Successfully Updated the Data")
                msg.setWindowTitle("Update")
                msg.exec_()
                mydb.commit()
                self.loadAll()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("Invalid Data")
            msg.setInformativeText("Please check all the input data is valid\n Verify the following:\n1. Name should "
                                   "contain first name,middlename and lastname\n2. Phone number and whatsapp number "
                                   "should consist of digits only\n3. Address, Education, Experience should not "
                                   "contain and not alphabetic characters except '-' amd space\n4. Email should be in "
                                   "format xyz@abc.lmn only")
            msg.setWindowTitle("Update")
            msg.exec_()

    def searchOnName(self):
        mycursor = mydb.cursor()
        if self.searchByComboBox.currentIndex() == 0:
            searchCharacter = self.searchInput.text()
            sql = "SELECT * FROM student_info_table WHERE first_name LIKE '%" + searchCharacter + "%' or middle_name LIKE '%" + searchCharacter + "%' or last_name LIKE '%" + searchCharacter + "%'"
            mycursor.execute(sql)
            result = mycursor.fetchall()
            row = 0
            self.searchDataTable.setRowCount(mycursor.rowcount)
            for x in result:
                fname = x[1]
                mname = x[2]
                lname = x[3]
                fullname = fname + " " + mname + " " + lname
                self.searchDataTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))
                self.searchDataTable.item(row, 0).setFlags(QtCore.Qt.ItemIsEnabled)
                self.searchDataTable.setItem(row, 1, QtWidgets.QTableWidgetItem(fullname))
                self.searchDataTable.setItem(row, 2, QtWidgets.QTableWidgetItem(x[4]))
                self.searchDataTable.setItem(row, 3, QtWidgets.QTableWidgetItem(x[5]))
                self.searchDataTable.setItem(row, 4, QtWidgets.QTableWidgetItem(str(x[8])))
                self.searchDataTable.setItem(row, 5, QtWidgets.QTableWidgetItem(x[6]))
                self.searchDataTable.setItem(row, 6, QtWidgets.QTableWidgetItem(str(x[7])))
                self.searchDataTable.item(row, 6).setFlags(QtCore.Qt.ItemIsEnabled)
                self.searchDataTable.setItem(row, 7, QtWidgets.QTableWidgetItem(x[9]))
                self.searchDataTable.setItem(row, 8, QtWidgets.QTableWidgetItem(x[10]))
                if x[11] is None:
                    self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem("None"))
                else:
                    self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem(x[11]))
                row += 1
            self.setTableSize()
        elif self.searchByComboBox.currentIndex() == 1:
            searchCharacter = self.searchInput.text()
            sql = "SELECT * FROM student_info_table WHERE phone LIKE '%" + searchCharacter + "%'"
            mycursor.execute(sql)
            result = mycursor.fetchall()
            row = 0
            self.searchDataTable.setRowCount(mycursor.rowcount)
            for x in result:
                fname = x[1]
                mname = x[2]
                lname = x[3]
                fullname = fname + " " + mname + " " + lname
                self.searchDataTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))
                self.searchDataTable.item(row, 0).setFlags(QtCore.Qt.ItemIsEnabled)
                self.searchDataTable.setItem(row, 1, QtWidgets.QTableWidgetItem(fullname))
                self.searchDataTable.setItem(row, 2, QtWidgets.QTableWidgetItem(x[4]))
                self.searchDataTable.setItem(row, 3, QtWidgets.QTableWidgetItem(x[5]))
                self.searchDataTable.setItem(row, 4, QtWidgets.QTableWidgetItem(str(x[8])))
                self.searchDataTable.setItem(row, 5, QtWidgets.QTableWidgetItem(x[6]))
                self.searchDataTable.setItem(row, 6, QtWidgets.QTableWidgetItem(str(x[7])))
                self.searchDataTable.item(row, 6).setFlags(QtCore.Qt.ItemIsEnabled)
                self.searchDataTable.setItem(row, 7, QtWidgets.QTableWidgetItem(x[9]))
                self.searchDataTable.setItem(row, 8, QtWidgets.QTableWidgetItem(x[10]))
                if x[11] is None:
                    self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem("None"))
                else:
                    self.searchDataTable.setItem(row, 9, QtWidgets.QTableWidgetItem(x[11]))
                row += 1
            self.setTableSize()

    def itemSelected(self):
        curRow = self.searchDataTable.currentRow()
        selectedName = "Selected Student: " + self.searchDataTable.item(curRow, 1).text()
        self.selectedStudentLabel.setText(selectedName)

    def setTableSize(self):
        header = self.searchDataTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(8, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(9, QtWidgets.QHeaderView.ResizeToContents)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.studentsInfoLabel.setText(_translate("MainWindow", "STUDENTS SECTION"))
        self.searchByLabel.setText(_translate("MainWindow", "Search By"))
        self.searchByComboBox.setItemText(0, _translate("MainWindow", "Name"))
        self.searchByComboBox.setItemText(1, _translate("MainWindow", "Phone Number"))
        self.searchLabel.setText(_translate("MainWindow", "Enter Student\'s Name"))
        self.selectedStudentLabel.setText(_translate("MainWindow", "Selected Student: None"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.cautionLabel.setText(
            _translate("MainWindow", "Before updating any data make that sure correct row is selected"))
        item = self.searchDataTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.searchDataTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.searchDataTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.searchDataTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Whatsapp No"))
        item = self.searchDataTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Address"))
        item = self.searchDataTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email"))
        item = self.searchDataTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Admission Date"))
        item = self.searchDataTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Education"))
        item = self.searchDataTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Experience"))
        item = self.searchDataTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Referred By"))
        self.backButton.setText(_translate("MainWindow", "Back"))

    def nameCheck(self, name):
        regex = "[A-Za-z ]+"
        if re.search(regex, name):
            return True
        else:
            return False

    def phoneCheck(self, phone):
        regex = "[0-9]+"
        if re.search(regex, phone):
            return True
        else:
            return False

    def addressCheck(self, name):
        regex = "[A-Za-z ]+"
        if re.search(regex, name):
            return True
        else:
            return False

    def emailCheck(self, email):
        regex = "^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w+$"
        if re.search(regex, email):
            return True
        else:
            return False

    # def dateCheck(self, date):
    #     regex = "^(20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$"
    #     if re.search(regex, date):
    #         return True
    #     else:
    #         return False

