# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from datetime import date

from PyQt5.QtWidgets import QCompleter

mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="local",
    password="",
    database="mpdev"
)

class Ui_UpdateBatchWindow(object):
    def setupUi(self, UpdateBatchWindow):
        UpdateBatchWindow.setObjectName("UpdateBatchWindow")
        UpdateBatchWindow.resize(1227, 870)
        UpdateBatchWindow.setStyleSheet("QMainWindow{\n"
                                        "background-color: #212121;\n"
                                        "}\n"
                                        "\n"
                                        "QWidget#globalCertTab{\n"
                                        "background-color: #212121;\n"
                                        "border-color: rgb(26, 255, 187);\n"
                                        "}\n"
                                        "QWidget#changeBatchTab{\n"
                                        "background-color: #212121;\n"
                                        "}\n"
                                        "QWidget#batchDateTab{\n"
                                        "background-color: #212121;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::pane { /* The tab widget frame */\n"
                                        "border: 2px solid #32e4c0;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::tab-bar {\n"
                                        "left: 5px; /* move to the right by 5px */\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::pane {\n"
                                        "    border: 2px solid #0d7377;\n"
                                        "    background: white;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::tab-bar:top {\n"
                                        "    top: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::tab-bar:bottom {\n"
                                        "    bottom: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::tab-bar:left {\n"
                                        "    right: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabWidget::tab-bar:right {\n"
                                        "    left: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab {\n"
                                        "    border: 1px solid black;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:selected {\n"
                                        "    background:#eeeeee;\n"
                                        "color: #0d7377;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:selected:hover{\n"
                                        "    background: white;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:!selected {\n"
                                        "    background: #0d7377;\n"
                                        "    color: rgb(238, 238, 238);\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:!selected:hover {\n"
                                        "    background: #32e4c0;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:top:!selected {\n"
                                        "    margin-top: 3px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:bottom:!selected {\n"
                                        "    margin-bottom: 3px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:top, QTabBar::tab:bottom {\n"
                                        "    min-width: 8ex;\n"
                                        "    margin-right: -1px;\n"
                                        "    padding: 5px 10px 5px 10px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:top:selected {\n"
                                        "    border-bottom-color: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:bottom:selected {\n"
                                        "    border-top-color: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
                                        "QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
                                        "    margin-right: 0;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:left:!selected {\n"
                                        "    margin-right: 3px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:right:!selected {\n"
                                        "    margin-left: 3px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:left, QTabBar::tab:right {\n"
                                        "    min-height: 8ex;\n"
                                        "    margin-bottom: -1px;\n"
                                        "    padding: 10px 5px 10px 5px;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:left:selected {\n"
                                        "    border-left-color: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:right:selected {\n"
                                        "    border-right-color: none;\n"
                                        "}\n"
                                        "\n"
                                        "QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
                                        "QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
                                        "    margin-bottom: 0;\n"
                                        "}")
        self.centralwidget = QtWidgets.QWidget(UpdateBatchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("QPushButton{\n"
                                     "background-color: #212121;\n"
                                     "Color: #eeeeee;\n"
                                     "border-radius: 20px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_2{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_2:hover{\n"
                                     "border: 3px solid rgb(255, 0, 0);\n"
                                     "background-color: #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_3{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_3:hover{\n"
                                     "border: 3px solid rgb(255, 0, 0);\n"
                                     "background-color: #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_4{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#backButton_4:hover{\n"
                                     "border: 3px solid rgb(255, 0, 0);\n"
                                     "background-color: #9a0002;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_2{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #008fd6;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_2:hover{\n"
                                     "border: 3px solid #005d8c;\n"
                                     "background-color: #00c8ff;\n"
                                     "color: #ffffff;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_3{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #008fd6;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_3:hover{\n"
                                     "border: 3px solid #005d8c;\n"
                                     "background-color: #00c8ff;\n"
                                     "color: #ffffff;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_4{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #008fd6;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#updateButton_4:hover{\n"
                                     "border: 3px solid #005d8c;\n"
                                     "background-color: #00c8ff;\n"
                                     "color: #ffffff;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#searchButton_2{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #32e0c4;\n"
                                     "border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#searchButton_2:hover{\n"
                                     "border: 3px solid #0d7377;\n"
                                     "background-color: #32e0c4;\n"
                                     "color: #ffffff;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#deleteButton{\n"
                                     "color: #eeeeee;\n"
                                     "background-color: #212121;\n"
                                     "border: 2px solid #ca8700;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#deleteButton:hover{\n"
                                     "border: 3px solid #ca8700;\n"
                                     "background-color: #ffaa00;\n"
                                     "color: #ffffff;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel{\n"
                                     "color: #eeeeee;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#globalCertUpdateLabel_2{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#batchInfoLabel{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "QLabel#changeStudentBatch{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#cautionLabel_2{\n"
                                     "color: rgb(255, 85, 0);\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#cautionLabel_3{\n"
                                     "color: rgb(255, 85, 0);\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#cautionLabel_4{\n"
                                     "color: rgb(255, 85, 0);\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#selectedStudentLabel_2{\n"
                                     "color:#aaffff;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#selectedStudentLabel_3{\n"
                                     "color:#aaffff;\n"
                                     "}\n"
                                     "QLabel#selectedBatchLabel{\n"
                                     "color:#aaffff;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#currentBatchLabel_2{\n"
                                     "color:#aaffff;\n"
                                     "}\n"
                                     "\n"
                                     "QLabel#helpLabel_2{\n"
                                     "color: #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox{\n"
                                     "border: 2px solid #0d7377;\n"
                                     "border-radius: 5px;\n"
                                     "padding-left: 4px;\n"
                                     "padding-right: 4px;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox:hover{\n"
                                     "border: 3px solid #32e0c4;\n"
                                     "}\n"
                                     "\n"
                                     "QComboBox QAbstractItemView {\n"
                                     "border: 2px solid #32e0c4;\n"
                                     "selection-background-color: #0d7377;\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit{\n"
                                     "padding-left: 6px;\n"
                                     "padding-right: 6px;\n"
                                     "border: 2px solid #0d7377;\n"
                                     "border-radius: 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QLineEdit:hover{\n"
                                     "border: 3px solid #32e0c4;\n"
                                     "}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.batchDateTab = QtWidgets.QWidget()
        self.batchDateTab.setObjectName("batchDateTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.batchDateTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.batchInfoLabel = QtWidgets.QLabel(self.batchDateTab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.batchInfoLabel.setFont(font)
        self.batchInfoLabel.setStyleSheet("")
        self.batchInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.batchInfoLabel.setObjectName("batchInfoLabel")
        self.verticalLayout_12.addWidget(self.batchInfoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_43 = QtWidgets.QLabel(self.batchDateTab)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_13.addWidget(self.label_43)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_44 = QtWidgets.QLabel(self.batchDateTab)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_27.addWidget(self.label_44)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.selectCourseLabel_4 = QtWidgets.QLabel(self.batchDateTab)
        self.selectCourseLabel_4.setMinimumSize(QtCore.QSize(300, 40))
        self.selectCourseLabel_4.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectCourseLabel_4.setFont(font)
        self.selectCourseLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.selectCourseLabel_4.setObjectName("selectCourseLabel_4")
        self.verticalLayout_14.addWidget(self.selectCourseLabel_4)
        self.courseComboBox_4 = QtWidgets.QComboBox(self.batchDateTab)
        self.courseComboBox_4.setMinimumSize(QtCore.QSize(300, 40))
        self.courseComboBox_4.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.courseComboBox_4.setFont(font)
        self.courseComboBox_4.setObjectName("courseComboBox_4")
        self.verticalLayout_14.addWidget(self.courseComboBox_4)
        self.horizontalLayout_27.addLayout(self.verticalLayout_14)
        self.label_45 = QtWidgets.QLabel(self.batchDateTab)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_27.addWidget(self.label_45)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_46 = QtWidgets.QLabel(self.batchDateTab)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_28.addWidget(self.label_46)
        self.selectedBatchLabel = QtWidgets.QLabel(self.batchDateTab)
        self.selectedBatchLabel.setMinimumSize(QtCore.QSize(600, 40))
        self.selectedBatchLabel.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.selectedBatchLabel.setFont(font)
        self.selectedBatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedBatchLabel.setObjectName("selectedBatchLabel")
        self.horizontalLayout_28.addWidget(self.selectedBatchLabel)
        self.label_47 = QtWidgets.QLabel(self.batchDateTab)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_28.addWidget(self.label_47)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem2)
        self.updateButton_4 = QtWidgets.QPushButton(self.batchDateTab)
        self.updateButton_4.setMinimumSize(QtCore.QSize(180, 40))
        self.updateButton_4.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton_4.setFont(font)
        self.updateButton_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.updateButton_4.setObjectName("updateButton_4")
        self.horizontalLayout_29.addWidget(self.updateButton_4)
        self.deleteButton = QtWidgets.QPushButton(self.batchDateTab)
        self.deleteButton.setMinimumSize(QtCore.QSize(180, 40))
        self.deleteButton.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteButton.setFont(font)
        self.deleteButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_29.addWidget(self.deleteButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_48 = QtWidgets.QLabel(self.batchDateTab)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_30.addWidget(self.label_48)
        self.cautionLabel_4 = QtWidgets.QLabel(self.batchDateTab)
        self.cautionLabel_4.setMinimumSize(QtCore.QSize(460, 40))
        self.cautionLabel_4.setMaximumSize(QtCore.QSize(460, 40))
        self.cautionLabel_4.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cautionLabel_4.setFont(font)
        self.cautionLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cautionLabel_4.setObjectName("cautionLabel_4")
        self.horizontalLayout_30.addWidget(self.cautionLabel_4)
        self.label_49 = QtWidgets.QLabel(self.batchDateTab)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_30.addWidget(self.label_49)
        self.verticalLayout_13.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_50 = QtWidgets.QLabel(self.batchDateTab)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_31.addWidget(self.label_50)
        self.backButton_4 = QtWidgets.QPushButton(self.batchDateTab)
        self.backButton_4.setMinimumSize(QtCore.QSize(180, 40))
        self.backButton_4.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_4.setFont(font)
        self.backButton_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton_4.setObjectName("backButton_4")
        self.horizontalLayout_31.addWidget(self.backButton_4)
        self.label_51 = QtWidgets.QLabel(self.batchDateTab)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_31.addWidget(self.label_51)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.label_52 = QtWidgets.QLabel(self.batchDateTab)
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.verticalLayout_13.addWidget(self.label_52)
        self.horizontalLayout_26.addLayout(self.verticalLayout_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(self.batchDateTab)
        self.line.setMinimumSize(QtCore.QSize(5, 0))
        self.line.setMaximumSize(QtCore.QSize(5, 16777215))
        self.line.setStyleSheet("background-color: rgb(50, 224, 196);\n"
                                "color: rgb(50, 224, 196);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_26.addWidget(self.line)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem6)
        self.label_53 = QtWidgets.QLabel(self.batchDateTab)
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.verticalLayout_15.addWidget(self.label_53)
        self.batchTable = QtWidgets.QTableWidget(self.batchDateTab)
        self.batchTable.setMinimumSize(QtCore.QSize(620, 0))
        self.batchTable.setMaximumSize(QtCore.QSize(620, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.batchTable.setFont(font)
        self.batchTable.setObjectName("batchTable")
        self.batchTable.setColumnCount(3)
        self.batchTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.batchTable.setHorizontalHeaderItem(2, item)
        self.batchTable.verticalHeader().setVisible(False)
        self.verticalLayout_15.addWidget(self.batchTable)
        self.label_54 = QtWidgets.QLabel(self.batchDateTab)
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.verticalLayout_15.addWidget(self.label_54)
        spacerItem7 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_26.addLayout(self.verticalLayout_15)
        self.verticalLayout_12.addLayout(self.horizontalLayout_26)
        self.label_55 = QtWidgets.QLabel(self.batchDateTab)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.verticalLayout_12.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.batchDateTab)
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.verticalLayout_12.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.batchDateTab)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.verticalLayout_12.addWidget(self.label_57)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 1, 2, 2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 3, 1, 1)
        self.tabWidget.addTab(self.batchDateTab, "")
        self.globalCertTab = QtWidgets.QWidget()
        self.globalCertTab.setObjectName("globalCertTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.globalCertTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.globalCertUpdateLabel_2 = QtWidgets.QLabel(self.globalCertTab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.globalCertUpdateLabel_2.setFont(font)
        self.globalCertUpdateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.globalCertUpdateLabel_2.setObjectName("globalCertUpdateLabel_2")
        self.verticalLayout_9.addWidget(self.globalCertUpdateLabel_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_29 = QtWidgets.QLabel(self.globalCertTab)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_19.addWidget(self.label_29)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.selectCourseLabel_3 = QtWidgets.QLabel(self.globalCertTab)
        self.selectCourseLabel_3.setMinimumSize(QtCore.QSize(300, 40))
        self.selectCourseLabel_3.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectCourseLabel_3.setFont(font)
        self.selectCourseLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.selectCourseLabel_3.setObjectName("selectCourseLabel_3")
        self.verticalLayout_10.addWidget(self.selectCourseLabel_3)
        self.courseComboBox_3 = QtWidgets.QComboBox(self.globalCertTab)
        self.courseComboBox_3.setEnabled(True)
        self.courseComboBox_3.setMinimumSize(QtCore.QSize(300, 40))
        self.courseComboBox_3.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.courseComboBox_3.setFont(font)
        self.courseComboBox_3.setObjectName("courseComboBox_3")
        self.verticalLayout_10.addWidget(self.courseComboBox_3)
        self.horizontalLayout_19.addLayout(self.verticalLayout_10)
        self.label_30 = QtWidgets.QLabel(self.globalCertTab)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_31 = QtWidgets.QLabel(self.globalCertTab)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_20.addWidget(self.label_31)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.selectBatchLabel_3 = QtWidgets.QLabel(self.globalCertTab)
        self.selectBatchLabel_3.setMinimumSize(QtCore.QSize(300, 40))
        self.selectBatchLabel_3.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectBatchLabel_3.setFont(font)
        self.selectBatchLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.selectBatchLabel_3.setObjectName("selectBatchLabel_3")
        self.verticalLayout_11.addWidget(self.selectBatchLabel_3)
        self.batchComboBox_3 = QtWidgets.QComboBox(self.globalCertTab)
        self.batchComboBox_3.setEnabled(True)
        self.batchComboBox_3.setMinimumSize(QtCore.QSize(300, 40))
        self.batchComboBox_3.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.batchComboBox_3.setFont(font)
        self.batchComboBox_3.setObjectName("batchComboBox_3")
        self.verticalLayout_11.addWidget(self.batchComboBox_3)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        self.label_32 = QtWidgets.QLabel(self.globalCertTab)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_20.addWidget(self.label_32)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_33 = QtWidgets.QLabel(self.globalCertTab)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_21.addWidget(self.label_33)
        self.selectedStudentLabel_3 = QtWidgets.QLabel(self.globalCertTab)
        self.selectedStudentLabel_3.setMinimumSize(QtCore.QSize(600, 40))
        self.selectedStudentLabel_3.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.selectedStudentLabel_3.setFont(font)
        self.selectedStudentLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedStudentLabel_3.setObjectName("selectedStudentLabel_3")
        self.horizontalLayout_21.addWidget(self.selectedStudentLabel_3)
        self.label_34 = QtWidgets.QLabel(self.globalCertTab)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_21.addWidget(self.label_34)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_35 = QtWidgets.QLabel(self.globalCertTab)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_22.addWidget(self.label_35)
        self.updateButton_3 = QtWidgets.QPushButton(self.globalCertTab)
        self.updateButton_3.setMinimumSize(QtCore.QSize(180, 40))
        self.updateButton_3.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton_3.setFont(font)
        self.updateButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.updateButton_3.setObjectName("updateButton_3")
        self.horizontalLayout_22.addWidget(self.updateButton_3)
        self.label_36 = QtWidgets.QLabel(self.globalCertTab)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_22.addWidget(self.label_36)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_37 = QtWidgets.QLabel(self.globalCertTab)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_23.addWidget(self.label_37)
        self.cautionLabel_3 = QtWidgets.QLabel(self.globalCertTab)
        self.cautionLabel_3.setMinimumSize(QtCore.QSize(460, 40))
        self.cautionLabel_3.setMaximumSize(QtCore.QSize(460, 40))
        self.cautionLabel_3.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cautionLabel_3.setFont(font)
        self.cautionLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cautionLabel_3.setObjectName("cautionLabel_3")
        self.horizontalLayout_23.addWidget(self.cautionLabel_3)
        self.label_38 = QtWidgets.QLabel(self.globalCertTab)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_23.addWidget(self.label_38)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_39 = QtWidgets.QLabel(self.globalCertTab)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_24.addWidget(self.label_39)
        self.globalCertTable = QtWidgets.QTableWidget(self.globalCertTab)
        self.globalCertTable.setMinimumSize(QtCore.QSize(650, 360))
        self.globalCertTable.setMaximumSize(QtCore.QSize(650, 360))
        self.globalCertTable.setObjectName("globalCertTable")
        self.globalCertTable.setColumnCount(3)
        self.globalCertTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.globalCertTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.globalCertTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.globalCertTable.setHorizontalHeaderItem(2, item)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.globalCertTable.setFont(font)
        self.horizontalLayout_24.addWidget(self.globalCertTable)
        self.label_40 = QtWidgets.QLabel(self.globalCertTab)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_24.addWidget(self.label_40)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_41 = QtWidgets.QLabel(self.globalCertTab)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_25.addWidget(self.label_41)
        self.backButton_3 = QtWidgets.QPushButton(self.globalCertTab)
        self.backButton_3.setMinimumSize(QtCore.QSize(180, 40))
        self.backButton_3.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_3.setFont(font)
        self.backButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton_3.setObjectName("backButton_3")
        self.horizontalLayout_25.addWidget(self.backButton_3)
        self.label_42 = QtWidgets.QLabel(self.globalCertTab)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_25.addWidget(self.label_42)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.globalCertTab, "")
        self.changeBatchTab = QtWidgets.QWidget()
        self.changeBatchTab.setObjectName("changeBatchTab")
        self.gridLayout = QtWidgets.QGridLayout(self.changeBatchTab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.changeStudentBatch = QtWidgets.QLabel(self.changeBatchTab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.changeStudentBatch.setFont(font)
        self.changeStudentBatch.setAlignment(QtCore.Qt.AlignCenter)
        self.changeStudentBatch.setObjectName("changeStudentBatch")
        self.verticalLayout_5.addWidget(self.changeStudentBatch)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem12)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.label_15 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.searchNameLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.searchNameLabel_2.setMinimumSize(QtCore.QSize(300, 40))
        self.searchNameLabel_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.searchNameLabel_2.setFont(font)
        self.searchNameLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.searchNameLabel_2.setObjectName("searchNameLabel_2")
        self.horizontalLayout_10.addWidget(self.searchNameLabel_2)
        self.label_16 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.nameInput_2 = QtWidgets.QLineEdit(self.changeBatchTab)
        self.nameInput_2.setMinimumSize(QtCore.QSize(300, 40))
        self.nameInput_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameInput_2.setFont(font)
        self.nameInput_2.setText("")
        self.nameInput_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.nameInput_2.setClearButtonEnabled(True)
        self.nameInput_2.setObjectName("nameInput_2")
        self.horizontalLayout_11.addWidget(self.nameInput_2)
        self.searchButton_2 = QtWidgets.QPushButton(self.changeBatchTab)
        self.searchButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.searchButton_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchButton_2.setFont(font)
        self.searchButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.searchButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton_2.setIcon(icon)
        self.searchButton_2.setObjectName("searchButton_2")
        self.horizontalLayout_11.addWidget(self.searchButton_2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.selectCourseLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.selectCourseLabel_2.setMinimumSize(QtCore.QSize(300, 40))
        self.selectCourseLabel_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectCourseLabel_2.setFont(font)
        self.selectCourseLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectCourseLabel_2.setObjectName("selectCourseLabel_2")
        self.verticalLayout_7.addWidget(self.selectCourseLabel_2)
        self.courseComboBox_2 = QtWidgets.QComboBox(self.changeBatchTab)
        self.courseComboBox_2.setEnabled(True)
        self.courseComboBox_2.setMinimumSize(QtCore.QSize(300, 40))
        self.courseComboBox_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.courseComboBox_2.setFont(font)
        self.courseComboBox_2.setObjectName("courseComboBox_2")
        self.verticalLayout_7.addWidget(self.courseComboBox_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.label_18 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem18 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.selectBatchLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.selectBatchLabel_2.setMinimumSize(QtCore.QSize(300, 40))
        self.selectBatchLabel_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.selectBatchLabel_2.setFont(font)
        self.selectBatchLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectBatchLabel_2.setObjectName("selectBatchLabel_2")
        self.verticalLayout_8.addWidget(self.selectBatchLabel_2)
        self.batchComboBox_2 = QtWidgets.QComboBox(self.changeBatchTab)
        self.batchComboBox_2.setEnabled(True)
        self.batchComboBox_2.setMinimumSize(QtCore.QSize(300, 40))
        self.batchComboBox_2.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.batchComboBox_2.setFont(font)
        self.batchComboBox_2.setObjectName("batchComboBox_2")
        self.verticalLayout_8.addWidget(self.batchComboBox_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.label_20 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.helpLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.helpLabel_2.setMinimumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.helpLabel_2.setFont(font)
        self.helpLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLabel_2.setObjectName("helpLabel_2")
        self.horizontalLayout_14.addWidget(self.helpLabel_2)
        self.label_22 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.selectedStudentLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.selectedStudentLabel_2.setMinimumSize(QtCore.QSize(600, 40))
        self.selectedStudentLabel_2.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.selectedStudentLabel_2.setFont(font)
        self.selectedStudentLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedStudentLabel_2.setObjectName("selectedStudentLabel_2")
        self.horizontalLayout_15.addWidget(self.selectedStudentLabel_2)
        self.label_24 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        self.currentBatchLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.currentBatchLabel_2.setMinimumSize(QtCore.QSize(600, 40))
        self.currentBatchLabel_2.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.currentBatchLabel_2.setFont(font)
        self.currentBatchLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentBatchLabel_2.setObjectName("currentBatchLabel_2")
        self.horizontalLayout_16.addWidget(self.currentBatchLabel_2)
        self.label_26 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_27 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_17.addWidget(self.label_27)
        self.cautionLabel_2 = QtWidgets.QLabel(self.changeBatchTab)
        self.cautionLabel_2.setMinimumSize(QtCore.QSize(460, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cautionLabel_2.setFont(font)
        self.cautionLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cautionLabel_2.setObjectName("cautionLabel_2")
        self.horizontalLayout_17.addWidget(self.cautionLabel_2)
        self.label_28 = QtWidgets.QLabel(self.changeBatchTab)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_17.addWidget(self.label_28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        spacerItem19 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem20)
        self.updateButton_2 = QtWidgets.QPushButton(self.changeBatchTab)
        self.updateButton_2.setMinimumSize(QtCore.QSize(180, 40))
        self.updateButton_2.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton_2.setFont(font)
        self.updateButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.updateButton_2.setObjectName("updateButton_2")
        self.horizontalLayout_18.addWidget(self.updateButton_2)
        self.backButton_2 = QtWidgets.QPushButton(self.changeBatchTab)
        self.backButton_2.setMinimumSize(QtCore.QSize(180, 40))
        self.backButton_2.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_2.setFont(font)
        self.backButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.backButton_2.setObjectName("backButton_2")
        self.horizontalLayout_18.addWidget(self.backButton_2)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem21)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(264, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 2, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem23, 3, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 1, 1, 1, 1)
        self.tabWidget.addTab(self.changeBatchTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        UpdateBatchWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UpdateBatchWindow)
        self.statusbar.setObjectName("statusbar")
        UpdateBatchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UpdateBatchWindow)
        self.tabWidget.setCurrentIndex(0)
        mycursor = mydb.cursor(buffered=True)
        mycursor.execute("SELECT course_name FROM courses_table")
        result = mycursor.fetchall()
        for x in result:
            self.courseComboBox_4.addItem(x[0])  # TAB1
            self.courseComboBox_3.addItem(x[0])  # TAB2

        # TAB1
        self.courseComboBox_4.setCurrentIndex(-1)  # TAB1
        self.courseComboBox_4.currentIndexChanged.connect(self.loadBatches)  # TAB1
        self.batchTable.itemSelectionChanged.connect(self.itemSelected)  # TAB1
        self.updateButton_4.clicked.connect(self.updateInfo)
        self.deleteButton.clicked.connect(self.deleteBatch)
        self.setTableSize()

        # TAB2
        self.courseComboBox_3.setCurrentIndex(-1)  # TAB2
        self.curCourse = 0
        self.curBatch = 0
        self.courseComboBox_3.currentIndexChanged.connect(self.loadBatchesTab2)
        self.batchComboBox_3.currentIndexChanged.connect(self.loadStudentTab2)
        self.globalCertTable.itemSelectionChanged.connect(self.itemSelected)  # TAB1
        self.updateButton_3.clicked.connect(self.updateGlobalCert)

        # TAB3

        self.curCourseId = 0
        self.curBatchId = 0
        self.curBatchName = 0
        self.studentId = 0
        mycursor = mydb.cursor(buffered=True)
        mycursor.execute("SELECT first_name,middle_name,last_name FROM student_info_table")
        studentList = mycursor.fetchall()
        if len(studentList) != 0:
            lst = [' '.join(x) for x in studentList]
        else:
            lst = []
        completer = QCompleter(lst, self.nameInput_2)
        completer.setCaseSensitivity(QtCore.Qt.CaseInsensitive)
        completer.setFilterMode(QtCore.Qt.MatchContains)
        self.nameInput_2.setCompleter(completer)
        self.courseComboBox_2.setCurrentIndex(-1)
        self.batchComboBox_2.setCurrentIndex(-1)
        self.updateButton_2.clicked.connect(self.updateBatch)
        self.searchButton_2.clicked.connect(self.searchForName)
        self.courseComboBox_2.currentIndexChanged.connect(self.loadBatchesTab3)
        QtCore.QMetaObject.connectSlotsByName(UpdateBatchWindow)

    # FOR TAB 1
    def loadBatches(self):
        self.selectedBatchLabel.setText("Selected Batch: None")
        mycursor = mydb.cursor(buffered=True)
        curCourse = self.courseComboBox_4.currentText()
        sql = "SELECT b.batch_id, b.batch_name, b.start_date FROM batches_table b, courses_table c WHERE course_name = '" + curCourse + "' AND b.course_id = c.course_id"
        mycursor.execute(sql)
        lst = mycursor.fetchall()
        row = 0
        self.batchTable.setRowCount(mycursor.rowcount)
        for x in lst:
            self.batchTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))
            # self.batchTable.item(row, 0).setFlags(QtCore.Qt.ItemIsEnabled)
            self.batchTable.setItem(row, 1, QtWidgets.QTableWidgetItem(x[1]))
            # self.batchTable.item(row, 1).setFlags(QtCore.Qt.ItemIsEnabled)
            dateedit = QtWidgets.QDateEdit()
            dateedit.setDate(x[2])
            dateedit.setCalendarPopup(True)
            dateedit.setMinimumDate(date.today())
            self.batchTable.setCellWidget(row, 2, dateedit)
            row += 1
        self.setTableSize()

    def updateInfo(self):
        mycursor = mydb.cursor(buffered=True)
        curRow = self.batchTable.currentRow()
        updatedDate = self.batchTable.cellWidget(curRow, 2).date().toPyDate()
        id = int(self.batchTable.item(curRow, 0).text())
        sql = "UPDATE batches_table SET start_date = (%s) WHERE batch_id = (%s)"
        val = (updatedDate, id)
        mycursor.execute(sql, val)
        if mycursor.rowcount == 1:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Successfully Updated the Data")
            msg.setWindowTitle("Update")
            msg.exec_()
            mydb.commit()
            self.loadBatches()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("Data not Updated")
            msg.setWindowTitle("Update")
            msg.exec_()

    def deleteBatch(self):
        curRow = self.batchTable.currentRow()
        name = self.batchTable.item(curRow, 1).text()
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("Are you sure you want to delete Batch " + name)
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
        msg.buttonClicked.connect(self.msgbtn)
        msg.setWindowTitle("Update")
        msg.exec_()

    def msgbtn(self, i):
        if i.text() == "OK":
            curRow = self.batchTable.currentRow()
            id = int(self.batchTable.item(curRow, 0).text())
            name = self.batchTable.item(curRow, 1).text()
            mycursor = mydb.cursor(buffered=True)
            sql = "UPDATE student_course_batch SET batch_id = NULL, global_cert = 'No' WHERE batch_id = " + str(id)
            mycursor.execute(sql)
            sql = "DROP TABLE IF EXISTS " + name
            mycursor.execute(sql)
            sql = "DELETE FROM batches_table WHERE batch_id = " + str(id)
            mycursor.execute(sql)
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Successfully Deleted the Batch")
            msg.setWindowTitle("Delete")
            msg.exec_()
            mydb.commit()
        else:
            return

    # TAB 2

    def loadBatchesTab2(self):
        self.selectedStudentLabel_3.setText("Selected Student: None")
        self.batchComboBox_3.clear()
        mycursor = mydb.cursor(buffered=True)
        curCourseName = self.courseComboBox_3.currentText()
        sql = "SELECT course_id FROM courses_table WHERE course_name = '" + curCourseName + "'"
        mycursor.execute(sql)
        temp = mycursor.fetchone()
        self.curCourse = temp[0]
        sql = "SELECT batch_name FROM batches_table WHERE course_id = " + str(self.curCourse)
        mycursor.execute(sql)
        temp = mycursor.fetchall()
        for x in temp:
            self.batchComboBox_3.addItem(x[0])
        self.batchComboBox_3.setCurrentIndex(-1)
        mycursor.close()

    def loadStudentTab2(self):
        self.selectedStudentLabel_3.setText("Selected Student: None")
        curBatchName = self.batchComboBox_3.currentText()
        mycursor = mydb.cursor(buffered=True)
        sql = "SELECT st.student_id, st.first_name, st.middle_name, st.last_name, scb.global_cert, b.batch_id FROM " \
              "student_info_table st, batches_table b, student_course_batch scb WHERE st.student_id = scb.student_id " \
              "AND scb.batch_id = b.batch_id AND b.batch_name = '" + curBatchName + "'"
        mycursor.execute(sql)
        temp = mycursor.fetchall()
        row = 0
        self.globalCertTable.setRowCount(mycursor.rowcount)
        for x in temp:
            self.curBatch = x[5]
            print(self.curBatch)
            self.globalCertTable.setItem(row, 0, QtWidgets.QTableWidgetItem(str(x[0])))
            fullName = x[1] + " " + x[2] + " " + x[3]
            self.globalCertTable.setItem(row, 1, QtWidgets.QTableWidgetItem(fullName))
            self.globalCertTable.item(row, 1).setFlags(QtCore.Qt.ItemIsEnabled)
            comboBox = QtWidgets.QComboBox()
            comboBox.addItem("Yes")
            comboBox.addItem("No")
            if x[4] == "Yes":
                comboBox.setCurrentIndex(0)
            else:
                comboBox.setCurrentIndex(1)
            self.globalCertTable.setCellWidget(row, 2, comboBox)
            row += 1
        self.setTableSize()
        mycursor.close()

    def updateGlobalCert(self):
        if self.globalCertTable.currentRow() != -1:
            mycursor = mydb.cursor(buffered=True)
            curRow = self.globalCertTable.currentRow()
            certStatus = self.globalCertTable.cellWidget(curRow, 2).currentText()
            fullname = self.globalCertTable.item(curRow, 1).text()
            studId = self.globalCertTable.item(curRow, 0).text()
            sql = "UPDATE student_course_batch SET global_cert = (%s) WHERE student_id = (%s) AND batch_id = (%s)"
            val = (certStatus, int(studId), self.curBatch)
            print(val)
            mycursor.execute(sql, val)
            if mycursor.rowcount == 1:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText("Successfully updated the Global Certification Status for " + fullname)
                msg.setWindowTitle("Update")
                msg.exec_()
                mydb.commit()
                mycursor.close()
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                msg.setText("Global Certification Status not Updated")
                msg.setWindowTitle("Update")
                msg.exec_()
                mycursor.close()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("No Student row selected to update")
            msg.setWindowTitle("Warning")
            msg.exec_()

    # FOR TAB3

    def searchForName(self):
        if self.nameInput_2.text() == "":
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("Please Enter the name of the student before searching")
            msg.setWindowTitle("Warning")
            msg.exec_()
        else:
            curName = self.nameInput_2.text()
            curName = curName.strip()
            curName = tuple(curName.split(" "))
            if len(curName) != 3:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Warning)
                msg.setText("Invalid Name input")
                msg.setInformativeText(
                    "Make sure you are entering first name, middle name and last name of the student")
                msg.setWindowTitle("Warning")
                msg.exec_()
            else:
                self.courseComboBox_2.clear()
                mycursor = mydb.cursor(buffered=True)
                sql = "SELECT student_id FROM student_info_table WHERE first_name = (%s) AND middle_name = (%s) AND " \
                      "last_name = (%s) "
                mycursor.execute(sql, curName)
                studID = mycursor.fetchone()
                if mycursor.rowcount != 0:
                    self.nameInput_2.setStyleSheet("border: 2px solid #00ff00")
                    self.studentId = studID[0]
                    sql = "SELECT c.course_name FROM courses_table c, student_course_batch scb WHERE c.course_id = " \
                          "scb.course_id AND scb.student_id = " + str(studID[0])
                    mycursor.execute(sql)
                    temp = mycursor.fetchall()
                    # self.courseComboBox_2.setCurrentIndex(-1)
                    for x in temp:
                        self.courseComboBox_2.addItem(x[0])
                    self.currentBatchLabel_2.setText("Current Batch: None")
                    self.courseComboBox_2.setCurrentIndex(-1)
                    self.batchComboBox_2.setCurrentIndex(-1)
                else:
                    self.nameInput_2.setStyleSheet("border: 2px solid #ff0000")
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QtWidgets.QMessageBox.Warning)
                    msg.setText("Invalid Name input")
                    msg.setInformativeText(
                        "The student you are trying to search is not a part of this institute. Please check if you have entered valid name.")
                    msg.setWindowTitle("Warning")
                    msg.exec_()

    def loadBatchesTab3(self):
        self.batchComboBox_2.clear()
        mycursor = mydb.cursor(buffered=True)
        tdate = date.today()
        if self.courseComboBox_2.currentIndex() != -1:
            curCourseName = self.courseComboBox_2.currentText()
            sql = "SELECT course_id FROM courses_table WHERE course_name = '" + curCourseName + "'"
            mycursor.execute(sql)
            temp = mycursor.fetchone()
            self.curCourseId = temp[0]
            sql = "SELECT b.batch_name, b.batch_id FROM batches_table b, student_course_batch scb WHERE " \
                  "scb.student_id = (%s) AND scb.course_id = b.course_id AND scb.course_id = (%s) AND b.batch_id = scb.batch_id"
            val = (self.studentId, self.curCourseId)
            mycursor.execute(sql, val)
            temp = mycursor.fetchone()
            print(temp)
            if mycursor.rowcount != 0:
                self.curBatchName = temp[0]
                self.curBatchId = temp[1]
                self.currentBatchLabel_2.setText("Current Batch: " + temp[0])
                sql = "SELECT batch_name FROM batches_table WHERE course_id = (%s) and start_date > (%s)"
                val = (self.curCourseId, tdate)
                mycursor.execute(sql, val)
                temp = mycursor.fetchall()
                for x in temp:
                    self.batchComboBox_2.addItem(x[0])
                mycursor.close()
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Warning)
                msg.setText("Add the student to the batch")
                msg.setInformativeText("No course has been alloted to the current student for the selected course.\n "
                                       "You can directly add the student to any batch from Batches Menu")
                msg.setWindowTitle("Warning")
                msg.exec_()

    def updateBatch(self):
        mycursor = mydb.cursor(buffered=True)
        if self.curBatch == self.batchComboBox_2.currentText():
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("Student is already present in this batch")
            msg.setWindowTitle("Warning")
            msg.exec_()
        else:
            sql = "DELETE FROM " + self.curBatchName + " WHERE student_id = " + str(self.studentId)
            # val = (self.curBatchName, self.studentId)
            mycursor.execute(sql)
            mydb.commit()
            curBatch = self.batchComboBox_2.currentText()
            sql = "SELECT batch_id FROM batches_table WHERE batch_name = '" + curBatch + "'"
            mycursor.execute(sql)
            bid = mycursor.fetchone()
            sql = "UPDATE student_course_batch SET batch_id = (%s) WHERE student_id = (%s) AND batch_id = (%s)"
            val = (bid[0], self.studentId, self.curBatchId)
            mycursor.execute(sql, val)
            if mycursor.rowcount == 1:
                mydb.commit()
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setText("Successfully updated the batch of student")
                msg.setInformativeText("Updated the batch from" + self.curBatchName + " to " + curBatch + " for course " + self.courseComboBox_2.currentText())
                msg.setWindowTitle("Update")
                msg.exec_()
                self.nameInput_2.clear()
                self.nameInput_2.setStyleSheet("border: 2px solid #0d7377")
                self.batchComboBox_2.clear()
                self.courseComboBox_2.clear()
                self.currentBatchLabel_2.setText("Current Batch: None")
                self.selectedStudentLabel_2.setText("Selected Student: None")
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                msg.setText("Batch not updated")
                msg.setWindowTitle("Update")
                msg.exec_()
                mycursor.close()


    # COMMON FOR ALL TABS

    def itemSelected(self):
        if self.tabWidget.currentIndex() == 0:
            curRow = self.batchTable.currentRow()
            selectedName = "Selected Batch: " + self.batchTable.item(curRow, 1).text()
            self.selectedBatchLabel.setText(selectedName)
        elif self.tabWidget.currentIndex() == 1:
            if self.globalCertTable.currentRow() != -1:
                curRow = self.globalCertTable.currentRow()
                selectedName = "Selected Student: " + self.globalCertTable.item(curRow, 1).text()
                self.selectedStudentLabel_3.setText(selectedName)
            else:
                self.selectedStudentLabel_3.setText("Selected Student: None")

    def setTableSize(self):
        if self.tabWidget.currentIndex() == 0:
            header = self.globalCertTable.horizontalHeader()
            header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
            header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
            header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        elif self.tabWidget.currentIndex() == 1:
            header = self.batchTable.horizontalHeader()
            header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
            header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
            header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)

    def retranslateUi(self, UpdateBatchWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateBatchWindow.setWindowTitle(_translate("UpdateBatchWindow", "MainWindow"))
        self.batchInfoLabel.setText(_translate("UpdateBatchWindow", "BATCHES SECTION"))
        self.selectCourseLabel_4.setText(_translate("UpdateBatchWindow", "Select Course"))
        self.selectedBatchLabel.setText(_translate("UpdateBatchWindow", "Selected Batch: None"))
        self.updateButton_4.setText(_translate("UpdateBatchWindow", "Update"))
        self.deleteButton.setText(_translate("UpdateBatchWindow", "Delete"))
        self.cautionLabel_4.setText(
            _translate("UpdateBatchWindow", "Before updating or deleting any data make sure correct row is selected. "
                                            "Click on Id to select any row."))

        self.backButton_4.setText(_translate("UpdateBatchWindow", "Back"))
        item = self.batchTable.horizontalHeaderItem(0)
        item.setText(_translate("UpdateBatchWindow", "Id"))
        item = self.batchTable.horizontalHeaderItem(1)
        item.setText(_translate("UpdateBatchWindow", "Batch Name"))
        item = self.batchTable.horizontalHeaderItem(2)
        item.setText(_translate("UpdateBatchWindow", "Date of Commencement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.batchDateTab),
                                  _translate("UpdateBatchWindow", "Batch Date"))
        self.globalCertUpdateLabel_2.setText(_translate("UpdateBatchWindow", "GLOBAL CERTIFICATION"))
        self.selectCourseLabel_3.setText(_translate("UpdateBatchWindow", "Select Course"))
        self.selectBatchLabel_3.setText(_translate("UpdateBatchWindow", "Select Batch"))
        self.selectedStudentLabel_3.setText(_translate("UpdateBatchWindow", "Selected Student: None"))
        self.updateButton_3.setText(_translate("UpdateBatchWindow", "Update"))
        self.cautionLabel_3.setText(
            _translate("UpdateBatchWindow",
                       "Before updating or deleting any data make sure correct row is selected. Click on Id to select any row."))
        item = self.globalCertTable.horizontalHeaderItem(0)
        item.setText(_translate("UpdateBatchWindow", "Id"))
        item = self.globalCertTable.horizontalHeaderItem(1)
        item.setText(_translate("UpdateBatchWindow", "Student Name"))
        item = self.globalCertTable.horizontalHeaderItem(2)
        item.setText(_translate("UpdateBatchWindow", "Global Certification"))
        self.backButton_3.setText(_translate("UpdateBatchWindow", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.globalCertTab),
                                  _translate("UpdateBatchWindow", "Global Certification Status"))
        self.changeStudentBatch.setText(_translate("UpdateBatchWindow", "CHANGE STUDENT BATCH"))
        self.searchNameLabel_2.setText(_translate("UpdateBatchWindow", "Search Student\'s Name"))
        self.nameInput_2.setPlaceholderText(_translate("UpdateBatchWindow", "Search here"))
        self.selectCourseLabel_2.setText(_translate("UpdateBatchWindow", "Select Course"))
        self.selectBatchLabel_2.setText(_translate("UpdateBatchWindow", "Select Batch"))
        self.helpLabel_2.setText(_translate("UpdateBatchWindow", "Above batches can be alloted to the student"))
        self.selectedStudentLabel_2.setText(_translate("UpdateBatchWindow", "Selected Student: None"))
        self.currentBatchLabel_2.setText(_translate("UpdateBatchWindow", "Current Batch: None"))
        self.cautionLabel_2.setText(
            _translate("UpdateBatchWindow", "Make sure correct student and batch is selected before updating"))
        self.updateButton_2.setText(_translate("UpdateBatchWindow", "Update"))
        self.backButton_2.setText(_translate("UpdateBatchWindow", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.changeBatchTab),
                                  _translate("UpdateBatchWindow", "Change Batch of Student"))


import updateBatch_rc
